version: "2.4"
services:
  parrot-html5:
    build: ./
    image: parrot-html5
    container_name: parrot-html5
    ports:
    - 80:6080
    environment:
    - VNC_PASSWORD=UQcyNFQ
    - ROOT_PASSWORD=UQcyNFQ
    - XUSER_PASSWORD=UQcyNFQ
    cap_add:
      - NET_ADMIN
    restart: always
    volumes:
    - ./home:/home/xuser